---

- hosts: all
  sudo: yes
  gather_facts: False
  vars:
    # python
    python_versions: [3.6]
    python_install: [django]
    #rsync_app
    app_user: ubuntu
    app_dir: /var/www/wedding/
    # venv
    venv_dir: /opt/virtual_env/
    venv_user: ubuntu
    venv_working_directory: /var/www/wedding/
    #nginx
    nginx_service_name: wedding
    nginx_service_port: 8000
    nginx_static_dir: /var/www/wedding/static_root
    nginx_media_dir: /var/www/wedding/photo/uploads
    nginx_server_name: kelseyanddain.com
    # systemd
    systemd_working_directory: /var/www/wedding/
    systemd_logdir: /var/log/wedding
    systemd_logto: /var/log/wedding/wedding.log
    systemd_service_name: wedding
    systemd_service_user: ubuntu
    systemd_service_settings_file: bigday.settings
    systemd_service_port: 8000
    systemd_venv_dir: /opt/virtual_env

  pre_tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: install pip
      apt: name=python-pip state=present

    - name: install setuptools
      shell: pip install setuptools

    - name: Gathering Facts
      setup:

  roles:
    - { role: common }
    - { role: python }
    - { role: rsync_app }
    - { role: venv }
    - { role: nginx }
    - { role: systemd }

  tasks:
    - file:
        path: /var/www/wedding/db.sqlite3
        owner: ubuntu
        group: ubuntu
        # when specifying mode using octal numbers, add a leading 0
        mode: 0777

    - name: Collect static files.
      shell: source {{ venv_dir }}bin/activate && make static
      args:
        chdir: /var/www/wedding
        executable: /bin/bash

    - name: Setup the App.
      shell: source {{ venv_dir }}bin/activate && make deps && make db_migrate
      args:
        chdir: /var/www/wedding
        executable: /bin/bash

    - name: Restart the app.
      service: name=wedding state=restarted
