---
systemd_working_directory: /vagrant/wedding
systemd_logdir: /var/log/wedding
systemd_logto: /var/log/wedding/wedding.log
systemd_service_name: wedding
systemd_service_user: vagrant
systemd_service_settings_file: bigday.settings
systemd_service_port: 8000
systemd_venv_dir: /opt/virtual_env
