# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 17:30
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=250)),
                ('photo', models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(), upload_to='photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
