# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 21:00
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(choices=[('hero', 'Hero'), ('story', 'Our Story'), ('adler', 'Adler Planetarium'), ('wedding_party', 'Wedding Party')], max_length=250),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(), upload_to='photo/uploads'),
        ),
    ]
