# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-25 16:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_sitesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesection',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
