# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_party_rehearsal_dinner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_1', models.CharField(max_length=200)),
                ('street_2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='guests.Guest')),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
    ]
